from __future__ import annotations

from typing import Any


SAMPLE_DOCUMENTS: list[dict[str, Any]] = [
    {
        "document_id": "movie_1275779:overview",
        "title_id": "movie_1275779",
        "title_name": "Disclosure Day",
        "content_type": "movie",
        "release_year": 2026,
        "genres": ["Science Fiction", "Thriller"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "A whistleblower uncovers evidence of extraterrestrial life and exposes a corporate and government cover-up.",
    },
    {
        "document_id": "movie_687163:overview",
        "title_id": "movie_687163",
        "title_name": "Project Hail Mary",
        "content_type": "movie",
        "release_year": 2026,
        "genres": ["Science Fiction", "Drama"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "A scientist wakes alone in space with amnesia and must solve a stellar crisis to save the Sun and humanity.",
    },
    {
        "document_id": "tv_259909:overview",
        "title_id": "tv_259909",
        "title_name": "Dexter: Resurrection",
        "content_type": "tv",
        "release_year": 2025,
        "genres": ["Crime", "Drama"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "After waking from a coma, a serial killer travels through New York while searching for his missing son.",
    },
    {
        "document_id": "movie_1288341:overview",
        "title_id": "movie_1288341",
        "title_name": "Seven Snipers",
        "content_type": "movie",
        "release_year": 2026,
        "genres": ["Action", "Thriller"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "A former assassin protects her daughter from the warlord who once held her captive.",
    },
    {
        "document_id": "movie_1398050:overview",
        "title_id": "movie_1398050",
        "title_name": "Driver's Ed",
        "content_type": "movie",
        "release_year": 2026,
        "genres": ["Comedy", "Drama"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "Teenagers steal a car and take a chaotic road trip to reunite their heartbroken friend with his college girlfriend.",
    },
    {
        "document_id": "movie_1020047:overview",
        "title_id": "movie_1020047",
        "title_name": "In the Hand of Dante",
        "content_type": "movie",
        "release_year": 2025,
        "genres": ["Mystery", "Drama"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "A rare medieval manuscript is stolen from the Vatican shortly after experts authenticate it.",
    },
    {
        "document_id": "tv_sample_obsession:overview",
        "title_id": "tv_sample_obsession",
        "title_name": "Obsession",
        "content_type": "tv",
        "release_year": 2025,
        "genres": ["Drama", "Thriller"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "A tense relationship becomes a public obsession as secrets, ambition, and anxiety collide.",
    },
    {
        "document_id": "movie_sample_leviticus:overview",
        "title_id": "movie_sample_leviticus",
        "title_name": "Leviticus",
        "content_type": "movie",
        "release_year": 2026,
        "genres": ["Drama", "Mystery"],
        "source_name": "sample",
        "document_type": "overview",
        "source_url": "",
        "text": "A mysterious family conflict explores identity, faith, responsibility, and reconciliation.",
    },
]


def sample_documents() -> list[dict[str, Any]]:
    """Return independent copies so callers can safely add run metadata."""
    return [dict(document) for document in SAMPLE_DOCUMENTS]
